#==============================================================================
# @file Variant.dscinc
# SM8250 Loader package.
#
# Copyright (c) 2017 Qualcomm Technologies, Inc. All rights reserved.
# Portions Copyright (c) 2009 - 2010, Apple Inc. All rights reserved.
# This program and the accompanying materials
# are licensed and made available under the terms and conditions of the BSD License
# which accompanies this distribution.  The full text of the license may be found at
# http://opensource.org/licenses/bsd-license.php
#
# THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
# WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
#==============================================================================


[LibraryClasses.common]
  DDRTargetLib|QcomPkg/SocPkg/8250/Library/DDRTargetLib/DDRTargetLibLP5.inf
  DSFTargetLib|QcomPkg/SocPkg/8250/Library/DSFTargetLib/DSFTargetLibLP5.inf
  DDITargetLib|QcomPkg/SocPkg/8250/Library/DDITargetLib/DDITargetLib.inf
  DDRSdiLib|QcomPkg/SocPkg/8250/Library/DDRTargetLib/DDRSdiLibLP5.inf
  DDRFwLib|QcomPkg/SocPkg/8250/Library/DSFTargetLib/DDRFwLibLP5.inf
  DDRFwSdiLib|QcomPkg/SocPkg/8250/Library/DSFTargetLib/DDRFwSdiLibLP5.inf